### PR TITLE
Fix issues with multi monitor support in setAnchor

### PR DESCRIPTION
**Pull request by AndrewSwerlick**
The set anchor function had a bug in that it did not account for the fact that
phoenix may have negative values for x and y in some multi monitor situations.
To resolve the issue, I replaced all areas where set anchor assumed the left
most or top most value would be 0 with calls to frame.x and frame.y

I believe this may fix bug #3, but since there weren't a lot of details in that bug 
I'm not sure.

### CODE REVIEW

**Comment by fabiospampinato** [comment]
Does this fix all the problems I listed in #3? Have you tested it yourself?

**Comment by AndrewSwerlick** [comment]
Looking at it again, it may not be related. The problems I saw weren't related to modals or growing and shrinking, they were problems with using halves, and anchors when a second display positioned to the left of my main display. I'll test some of the other features again later tonight and confirm.

**Comment by AndrewSwerlick** [comment]
Did some more testing and pushed up another set of changes that deals with the growFrame problems. It's the same class of bug. Tested with a few different monitor set ups, particular odd veritical arrangments where the external monitor was "below" the primary monitor.

There's still a problem with centering, but I'm betting it's the same class of bug. I'll look at it later this week.

**Comment by AndrewSwerlick** [comment]
Actually, couldn't leave it well enough alone tonight. The centering issue was just a problem with using `frame` and not `flippedFrame`. Not sure about the modals, haven't been able to replicate any issues there

**Comment by Dorian8013** [comment]
@fabiospampinato I've been plagued by this multi-monitor issue since it became a problem. I applied this PR for the helpers to my installation, and now multi-monitor support is working (#3)!

I tested this by walking through the README and testing each of the described functions on each of my monitors. Before applying this fix, anything I would do on my secondary monitor would simply cause the active window to jump to my primary monitor. Now all of the behaviors take place on the original monitor.

I cannot remember if before the multi-monitor bug crept up it was possible to move a window between monitors. Perhaps I'll work on that and submit a PR

**Comment by jvivs** [comment]
Found this issue because I was also running into issues with a multi-monitor setup.

Using the examples in [README.md](https://github.com/fabiospampinato/phoenix/blob/16e98dbabde498b982f984380644e587bc0cedd5/README.md) as test case I've exercised the changeset and here's what I've found:

Primary: All resizing and moving works as expected.
Secondary: 
- sides, corners, halves, thirds, sixths all work
- X-axis growth works

- centering and resizing to 900x600 resizes correctly but locates the window at:
  - x: -50% screen + 50% window width
  - y: -50% screen

Here's my testbed and current screen arrangement:

Primary display: Macbook Pro 16 @ 1792 x 1120 (Native Retina)
Secondary display:  34" LG 21:9 @ 3440 x 1440 (Native)
OS: MacOS 10.15.4

Screen Shot 2020-05-25 at 4 40 02 PM

**Comment by jvivs** [comment]
Resolved centering bug by:
- bounding the respective dimensions of the window to the dimensions of the screen
- computing center of screen (height /2, width /2) 
- computing topLeft of window relative to computed center of screen

Working through the issue with frame growth. I'll open up a PR with a changeset that builds upon @AndrewSwerlick's fixes here.

**Comment by fabiospampinato** [comment]
Most of the issues with multi-monitors setups have been addressed in the latest commits.

**Pull request closed without merging**
